// shortcuts.js
window.shortcuts = [
  { name: '段落', tag: '<p></p>', desc: '插入段落标签' },
  { name: '超链接', tag: "<a href=''>超链接</a>", desc: '插入超链接标签' },
  { name: '!DOCTYPE html', tag: '<!DOCTYPE html>', desc: '插入文档类型声明' },
  { name: '缩写', tag: '<abbr></abbr>', desc: '插入缩写标签' },
  { name: '地址', tag: '<address></address>', desc: '插入地址标签' },
  { name: '图像映射区域', tag: '<area>', desc: '插入图像映射区域' },
  { name: '文章', tag: '<article></article>', desc: '插入文章标签' },
  { name: '侧边栏', tag: '<aside></aside>', desc: '插入侧边栏标签' },
  { name: '音乐', tag: "<audio src='audio.mp3' controls>不支持音频</audio>", desc: '插入音乐标签' },
  { name: '背景音乐', tag: "<audio src='background.mp3' autoplay loop hidden></audio>", desc: '插入背景音乐标签' },
  { name: '插入视频', tag: "<audio src='audio.mp3' controls>不支持音频</audio>", desc: '插入视频标签（应为 video）' },
  { name: '图片', tag: "<img src='img.jpg' alt='示例图片' width=20%>", desc: '插入图片标签' },
  { name: '图片说明文字', tag: `<figure>\n  <img src='img.jpg' alt='示例图片' width=20%>\n  <figcaption>图片说明文字</figcaption>\n</figure>`, desc: '插入带说明的图片' },
  { name: '粗体', tag: '<b></b>', desc: '插入粗体标签' },
  { name: '基准URL', tag: '<base>', desc: '插入基准URL标签' },
  { name: '文本方向隔离', tag: '<bdi></bdi>', desc: '插入文本方向隔离标签' },
  { name: '文本方向覆盖', tag: '<bdo></bdo>', desc: '插入文本方向覆盖标签' },
  { name: '块引用', tag: '<blockquote></blockquote>', desc: '插入块引用标签' },
  { name: '文档主体', tag: '<body></body>', desc: '插入文档主体标签' },
  { name: '换行', tag: '<br>', desc: '插入换行标签' },
  { name: '按钮', tag: '<button></button>', desc: '插入按钮标签' },
  { name: '画布', tag: '<canvas></canvas>', desc: '插入画布标签' },
  { name: '表格标题', tag: '<caption></caption>', desc: '插入表格标题标签' },
  { name: '引用来源', tag: '<cite></cite>', desc: '插入引用来源标签' },
  { name: '代码', tag: '<pre><code></code></pre>', desc: '插入代码块' },
  { name: '表格列', tag: '<col>', desc: '插入表格列标签' },
  { name: '表格列组', tag: '<colgroup></colgroup>', desc: '插入表格列组标签' },
  { name: '机器可读数据', tag: '<data></data>', desc: '插入机器可读数据标签' },
  { name: '选项列表', tag: '<datalist></datalist>', desc: '插入选项列表标签' },
  { name: '定义描述', tag: '<dd></dd>', desc: '插入定义描述标签' },
  { name: '删除文本', tag: '<del></del>', desc: '插入删除文本标签' },
  { name: '详细信息', tag: '<details></details>', desc: '插入详细信息标签' },
  { name: '定义术语', tag: '<dfn></dfn>', desc: '插入定义术语标签' },
  { name: '对话框', tag: '<dialog></dialog>', desc: '插入对话框标签' },
  { name: '分区', tag: '<div></div>', desc: '插入分区标签' },
  { name: '定义列表', tag: '<dl></dl>', desc: '插入定义列表标签' },
  { name: '定义术语', tag: '<dt></dt>', desc: '插入定义术语标签' },
  { name: '强调', tag: '<em></em>', desc: '插入强调标签' },
  { name: '嵌入内容', tag: '<embed>', desc: '插入嵌入内容标签' },
  { name: '表单分组', tag: '<fieldset></fieldset>', desc: '插入表单分组标签' },
  { name: '图例标题', tag: '<figcaption></figcaption>', desc: '插入图例标题标签' },
  { name: '图例', tag: '<figure></figure>', desc: '插入图例标签' },
  { name: '页脚', tag: '<footer></footer>', desc: '插入页脚标签' },
  { name: '表单', tag: '<form></form>', desc: '插入表单标签' },
  { name: '标题1', tag: '<h1></h1>', desc: '插入标题1标签' },
  { name: '标题2', tag: '<h2></h2>', desc: '插入标题2标签' },
  { name: '标题3', tag: '<h3></h3>', desc: '插入标题3标签' }
];
